package com.TAC.Model;

// Generated 2015-8-30 16:35:56 by Hibernate Tools 4.3.1

/**
 * Iteminfo generated by hbm2java
 */
public class Iteminfo implements java.io.Serializable {

	public Integer id;
	public String name;
	public String description;
	public String type;
	public int count;
	public int leftcount;

	public Iteminfo() {
	}

	public Iteminfo(String name, String type, int count, int leftcount) {
		this.name = name;
		this.type = type;
		this.count = count;
		this.leftcount = leftcount;
	}

	public Iteminfo(String name, String description, String type, int count,
			int leftcount) {
		this.name = name;
		this.description = description;
		this.type = type;
		this.count = count;
		this.leftcount = leftcount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public int getLeftcount() {
		return this.leftcount;
	}

	public void setLeftcount(int leftcount) {
		this.leftcount = leftcount;
	}

}
